/****** Object:  Table [dbo].[Products]    Script Date: 13.01.2019 20:31:15 ******/
CREATE TABLE [dbo].[Products](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[ProductCode] [nvarchar](15) NOT NULL,
	[ProductBarcode] [nvarchar](15) NULL,
	[ProductLabel] [nvarchar](20) NULL,
	[ProductName] [nvarchar](60) NOT NULL,
	[ProductImage] [nvarchar](255) NULL,
	[SupplierID] [int] NULL,
	[CounterpartyID] [nvarchar](14) NULL,
	[CategoryID] [int] NULL,
	[MeasureID] [int] NOT NULL,
	[QuantityPerUnit] [nvarchar](20) NULL,
	[UnitPrice] [money] NULL,
	[UnitsInStock] [smallint] NULL,
	[UnitsOnOrder] [smallint] NULL,
	[ReorderLevel] [smallint] NULL,
	[Discontinued] [bit] NOT NULL,
	[InsertDate] [datetime] NOT NULL,
	[InsertUserId] [int] NOT NULL,
	[UpdateDate] [datetime] NULL,
	[UpdateUserId] [int] NULL,
	[IsActive] [int] NOT NULL,
	[TenantId] [int] NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Products] ON 

INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (1, N' ', N'Chai', NULL, 1, 1, 1, N'10 boxes x 20 bags', 18.0000, 39, 0, 10, 0, CAST(N'2019-01-07T13:48:01.410' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (2, N' ', N'Chang', NULL, 1, 1, 1, N'24 - 12 oz bottles', 19.0000, 17, 40, 25, 0, CAST(N'2019-01-07T13:48:01.410' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (3, N' ', N'Aniseed Syrup', NULL, 1, 2, 1, N'12 - 550 ml bottles', 10.0000, 13, 70, 25, 0, CAST(N'2019-01-07T13:48:01.410' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (4, N' ', N'Chef Anton''s Cajun Seasoning', NULL, 2, 2, 1, N'48 - 6 oz jars', 22.0000, 53, 0, 0, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (5, N' ', N'Chef Anton''s Gumbo Mix', NULL, 2, 2, 1, N'36 boxes', 21.3500, 0, 0, 0, 1, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (6, N' ', N'Grandma''s Boysenberry Spread', NULL, 3, 2, 1, N'12 - 8 oz jars', 25.0000, 120, 0, 25, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (7, N' ', N'Uncle Bob''s Organic Dried Pears', NULL, 3, 7, 1, N'12 - 1 lb pkgs.', 30.0000, 15, 0, 10, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (8, N' ', N'Northwoods Cranberry Sauce', NULL, 3, 2, 1, N'12 - 12 oz jars', 40.0000, 6, 0, 0, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (9, N' ', N'Mishi Kobe Niku', NULL, 4, 6, 1, N'18 - 500 g pkgs.', 97.0000, 29, 0, 0, 1, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (10, N' ', N'Ikura', NULL, 4, 8, 1, N'12 - 200 ml jars', 31.0000, 31, 0, 0, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (11, N' ', N'Queso Cabrales', NULL, 5, 4, 1, N'1 kg pkg.', 21.0000, 22, 30, 30, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (12, N' ', N'Queso Manchego La Pastora', NULL, 5, 4, 1, N'10 - 500 g pkgs.', 38.0000, 86, 0, 0, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (13, N' ', N'Konbu', NULL, 6, 8, 1, N'2 kg box', 6.0000, 24, 0, 5, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (14, N' ', N'Tofu', NULL, 6, 7, 1, N'40 - 100 g pkgs.', 23.2500, 35, 0, 0, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (15, N' ', N'Genen Shouyu', NULL, 6, 2, 1, N'24 - 250 ml bottles', 15.5000, 39, 0, 5, 0, CAST(N'2019-01-07T13:48:01.413' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (16, N' ', N'Pavlova', NULL, 7, 3, 1, N'32 - 500 g boxes', 17.4500, 29, 0, 10, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (17, N' ', N'Alice Mutton', NULL, 7, 6, 1, N'20 - 1 kg tins', 39.0000, 0, 0, 0, 1, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (18, N' ', N'Carnarvon Tigers', NULL, 7, 8, 1, N'16 kg pkg.', 62.5000, 42, 0, 0, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (19, N' ', N'Teatime Chocolate Biscuits', NULL, 8, 3, 1, N'10 boxes x 12 pieces', 9.2000, 25, 0, 5, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (20, N' ', N'Sir Rodney''s Marmalade', NULL, 8, 3, 1, N'30 gift boxes', 81.0000, 40, 0, 0, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (21, N' ', N'Sir Rodney''s Scones', NULL, 8, 3, 1, N'24 pkgs. x 4 pieces', 10.0000, 3, 40, 5, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (22, N' ', N'Gustaf''s Knäckebröd', NULL, 9, 5, 1, N'24 - 500 g pkgs.', 21.0000, 104, 0, 25, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (23, N' ', N'Tunnbröd', NULL, 9, 5, 1, N'12 - 250 g pkgs.', 9.0000, 61, 0, 25, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (24, N' ', N'Guaraná Fantástica', NULL, 10, 1, 1, N'12 - 355 ml cans', 4.5000, 20, 0, 0, 1, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (25, N' ', N'NuNuCa Nuß-Nougat-Creme', NULL, 11, 3, 1, N'20 - 450 g glasses', 14.0000, 76, 0, 30, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (26, N' ', N'Gumbär Gummibärchen', NULL, 11, 3, 1, N'100 - 250 g bags', 31.2300, 15, 0, 0, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (27, N' ', N'Schoggi Schokolade', NULL, 11, 3, 1, N'100 - 100 g pieces', 43.9000, 49, 0, 30, 0, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (28, N' ', N'Rössle Sauerkraut', NULL, 12, 7, 1, N'25 - 825 g cans', 45.6000, 26, 0, 0, 1, CAST(N'2019-01-07T13:48:01.417' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (29, N' ', N'Thüringer Rostbratwurst', NULL, 12, 6, 1, N'50 bags x 30 sausgs.', 123.7900, 0, 0, 0, 1, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (30, N' ', N'Nord-Ost Matjeshering', NULL, 13, 8, 1, N'10 - 200 g glasses', 25.8900, 10, 0, 15, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (31, N' ', N'Gorgonzola Telino', NULL, 14, 4, 1, N'12 - 100 g pkgs', 12.5000, 0, 70, 20, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (32, N' ', N'Mascarpone Fabioli', NULL, 14, 4, 1, N'24 - 200 g pkgs.', 32.0000, 9, 40, 25, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (33, N' ', N'Geitost', NULL, 15, 4, 1, N'500 g', 2.5000, 112, 0, 20, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (34, N' ', N'Sasquatch Ale', NULL, 16, 1, 1, N'24 - 12 oz bottles', 14.0000, 111, 0, 15, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (35, N' ', N'Steeleye Stout', NULL, 16, 1, 1, N'24 - 12 oz bottles', 18.0000, 20, 0, 15, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (36, N' ', N'Inlagd Sill', NULL, 17, 8, 1, N'24 - 250 g  jars', 19.0000, 112, 0, 20, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (37, N' ', N'Gravad lax', NULL, 17, 8, 1, N'12 - 500 g pkgs.', 26.0000, 11, 50, 25, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (38, N' ', N'Côte de Blaye', NULL, 18, 1, 1, N'12 - 75 cl bottles', 263.5000, 17, 0, 15, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (39, N' ', N'Chartreuse verte', NULL, 18, 1, 1, N'750 cc per bottle', 18.0000, 69, 0, 5, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (40, N' ', N'Boston Crab Meat', NULL, 19, 8, 1, N'24 - 4 oz tins', 18.4000, 123, 0, 30, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (41, N' ', N'Jack''s New England Clam Chowder', NULL, 19, 8, 1, N'12 - 12 oz cans', 9.6500, 85, 0, 10, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (42, N' ', N'Singaporean Hokkien Fried Mee', NULL, 20, 5, 1, N'32 - 1 kg pkgs.', 14.0000, 26, 0, 0, 1, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (43, N' ', N'Ipoh Coffee', NULL, 20, 1, 1, N'16 - 500 g tins', 46.0000, 17, 10, 25, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (44, N' ', N'Gula Malacca', NULL, 20, 2, 1, N'20 - 2 kg bags', 19.4500, 27, 0, 15, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (45, N' ', N'Rogede sild', NULL, 21, 8, 1, N'1k pkg.', 9.5000, 5, 70, 15, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (46, N' ', N'Spegesild', NULL, 21, 8, 1, N'4 - 450 g glasses', 12.0000, 95, 0, 0, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (47, N' ', N'Zaanse koeken', NULL, 22, 3, 1, N'10 - 4 oz boxes', 9.5000, 36, 0, 0, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (48, N' ', N'Chocolade', NULL, 22, 3, 1, N'10 pkgs.', 12.7500, 15, 70, 25, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (49, N' ', N'Maxilaku', NULL, 23, 3, 1, N'24 - 50 g pkgs.', 20.0000, 10, 60, 15, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (50, N' ', N'Valkoinen suklaa', NULL, 23, 3, 1, N'12 - 100 g bars', 16.2500, 65, 0, 30, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (51, N' ', N'Manjimup Dried Apples', NULL, 24, 7, 1, N'50 - 300 g pkgs.', 53.0000, 20, 0, 10, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (52, N' ', N'Filo Mix', NULL, 24, 5, 1, N'16 - 2 kg boxes', 7.0000, 38, 0, 25, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (53, N' ', N'Perth Pasties', NULL, 24, 6, 1, N'48 pieces', 32.8000, 0, 0, 0, 1, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (54, N' ', N'Tourtière', NULL, 25, 6, 1, N'16 pies', 7.4500, 21, 0, 10, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (55, N' ', N'Pâté chinois', NULL, 25, 6, 1, N'24 boxes x 2 pies', 24.0000, 115, 0, 20, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (56, N' ', N'Gnocchi di nonna Alice', NULL, 26, 5, 1, N'24 - 250 g pkgs.', 38.0000, 21, 10, 30, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (57, N' ', N'Ravioli Angelo', NULL, 26, 5, 1, N'24 - 250 g pkgs.', 19.5000, 36, 0, 20, 0, CAST(N'2019-01-07T13:48:01.420' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (58, N' ', N'Escargots de Bourgogne', NULL, 27, 8, 1, N'24 pieces', 13.2500, 62, 0, 20, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (59, N' ', N'Raclette Courdavault', NULL, 28, 4, 1, N'5 kg pkg.', 55.0000, 79, 0, 0, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (60, N' ', N'Camembert Pierrot', NULL, 28, 4, 1, N'15 - 300 g rounds', 34.0000, 19, 0, 0, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (61, N' ', N'Sirop d''érable', NULL, 29, 2, 1, N'24 - 500 ml bottles', 28.5000, 113, 0, 25, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (62, N' ', N'Tarte au sucre', NULL, 29, 3, 1, N'48 pies', 49.3000, 17, 0, 0, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (63, N' ', N'Vegie-spread', NULL, 7, 2, 1, N'15 - 625 g jars', 43.9000, 24, 0, 5, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (64, N' ', N'Wimmers gute Semmelknödel', NULL, 12, 5, 1, N'20 bags x 4 pieces', 33.2500, 22, 80, 30, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (65, N' ', N'Louisiana Fiery Hot Pepper Sauce', NULL, 2, 2, 1, N'32 - 8 oz bottles', 21.0500, 76, 0, 0, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (66, N' ', N'Louisiana Hot Spiced Okra', NULL, 2, 2, 1, N'24 - 8 oz jars', 17.0000, 4, 100, 20, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (67, N' ', N'Laughing Lumberjack Lager', NULL, 16, 1, 1, N'24 - 12 oz bottles', 14.0000, 52, 0, 10, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (68, N' ', N'Scottish Longbreads', NULL, 8, 3, 1, N'10 boxes x 8 pieces', 12.5000, 6, 10, 15, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (69, N' ', N'Gudbrandsdalsost', NULL, 15, 4, 1, N'10 kg pkg.', 36.0000, 26, 0, 15, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (70, N' ', N'Outback Lager', NULL, 7, 1, 1, N'24 - 355 ml bottles', 15.0000, 15, 10, 30, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (71, N' ', N'Flotemysost', NULL, 15, 4, 1, N'10 - 500 g pkgs.', 21.5000, 26, 0, 0, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (72, N' ', N'Mozzarella di Giovanni', NULL, 14, 4, 1, N'24 - 200 g pkgs.', 34.8000, 14, 0, 0, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (73, N' ', N'Röd Kaviar', NULL, 17, 8, 1, N'24 - 150 g jars', 15.0000, 101, 0, 5, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (74, N' ', N'Longlife Tofu', NULL, 4, 7, 1, N'5 kg pkg.', 10.0000, 4, 20, 5, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (75, N' ', N'Rhönbräu Klosterbier', NULL, 12, 1,  1,N'24 - 0.5 l bottles', 7.7500, 125, 0, 25, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (76, N' ', N'Lakkalikööri', NULL, 23, 1, 1, N'500 ml', 18.0000, 57, 0, 20, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
INSERT [dbo].[Products] ([ProductID], [ProductCode], [ProductName], [ProductImage], [SupplierID], [CategoryID], [MeasureID], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [UnitsOnOrder], [ReorderLevel], [Discontinued], [InsertDate], [InsertUserId], [UpdateDate], [UpdateUserId], [IsActive], [TenantId]) VALUES (77, N' ', N'Original Frankfurter grüne Soße', NULL, 12, 2, 1, N'12 boxes', 13.0000, 32, 0, 15, 0, CAST(N'2019-01-07T13:48:01.423' AS DateTime), 1, NULL, NULL, 1, 1)
SET IDENTITY_INSERT [dbo].[Products] OFF
ALTER TABLE [dbo].[Products] ADD  CONSTRAINT [DF_Products_UnitPrice]  DEFAULT ((0)) FOR [UnitPrice]
GO
ALTER TABLE [dbo].[Products] ADD  CONSTRAINT [DF_Products_UnitsInStock]  DEFAULT ((0)) FOR [UnitsInStock]
GO
ALTER TABLE [dbo].[Products] ADD  CONSTRAINT [DF_Products_UnitsOnOrder]  DEFAULT ((0)) FOR [UnitsOnOrder]
GO
ALTER TABLE [dbo].[Products] ADD  CONSTRAINT [DF_Products_ReorderLevel]  DEFAULT ((0)) FOR [ReorderLevel]
GO
ALTER TABLE [dbo].[Products] ADD  CONSTRAINT [DF_Products_Discontinued]  DEFAULT ((0)) FOR [Discontinued]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT (getdate()) FOR [InsertDate]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT ((1)) FOR [InsertUserId]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT ((1)) FOR [TenantId]
GO
ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [FK_Products_Categories] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Categories] ([CategoryID])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Categories]
GO

ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [FK_Products_Suppliers] FOREIGN KEY([SupplierID])
REFERENCES [dbo].[Suppliers] ([SupplierID])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Suppliers]
GO

ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [FK_Product_Counterparties] FOREIGN KEY([CounterpartyID])
REFERENCES [dbo].[Counterparties] ([CounterpartyID])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Product_Counterparties]
GO

ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [FK_Product_Measures] FOREIGN KEY([MeasureID])
REFERENCES [dbo].[Measures] ([MeasureID])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Product_Measures]
GO

ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [CK_Products_UnitPrice] CHECK  (([UnitPrice]>=(0)))
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [CK_Products_UnitPrice]
GO
ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [CK_ReorderLevel] CHECK  (([ReorderLevel]>=(0)))
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [CK_ReorderLevel]
GO
ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [CK_UnitsInStock] CHECK  (([UnitsInStock]>=(0)))
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [CK_UnitsInStock]
GO
ALTER TABLE [dbo].[Products]  WITH NOCHECK ADD  CONSTRAINT [CK_UnitsOnOrder] CHECK  (([UnitsOnOrder]>=(0)))
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [CK_UnitsOnOrder]
GO

ALTER TABLE [dbo].[ProductMovement Details]  WITH NOCHECK ADD  CONSTRAINT [FK_ProductMovement_Details_Product] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
ALTER TABLE [dbo].[ProductMovement Details] CHECK CONSTRAINT [FK_ProductMovement_Details_Product]
GO

ALTER TABLE [dbo].[Product Details]  WITH NOCHECK ADD  CONSTRAINT [FK_Product Details_Products] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
ALTER TABLE [dbo].[Product Details] CHECK CONSTRAINT [FK_Product Details_Products]
GO

