version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=<DryRiver#958>
      - ACCEPT_EULA=Y
      - attach_dbs=
        [{"dbName":"Default","dbFiles":["D:\\sqldata\\Store_Default_v1.mdf","D:\\sqldata\\Store_Default_v1.ldf"]},
        [{"dbName":"Store","dbFiles":["D:\\sqldata\\Store_Store_v1.mdf","D:\\sqldata\\Store_Store_v1.ldf"]}]


  corestore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${Default:-Server=sqldata;Database=Store_Default_v1;User Id=SA;Password=<DryRiver#958>}
      - ConnectionString=${Store:-Server=sqldata;Database=Store_Store_v1;User Id=SA;Password=<DryRiver#958>}
    ports:
      - "80"


