version: '3.4'

services:
  store.web:
    ports:
      - "8000:80"
    depends_on:
      - sqldb
    deploy:
       replicas: 2

  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "Your_password123"
       ACCEPT_EULA: "Y"
    ports:
       - "2500:1433"
