//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Ledger")]
[assembly: System.Reflection.AssemblyCompany("Data Design")]
[assembly: System.Reflection.AssemblyProduct("Ledger")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Data Design © 2017")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("18.2.0.0b10400")]
[assembly: System.Reflection.AssemblyVersion("18.2.0")]
[assembly: System.Reflection.AssemblyFileVersion("18.2.0")]


