version: '3.4'

services:

  sqldata:
    image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
    container_name: mssql
    ports:
      - "1433:1433"


  corestore.web:
    image: hub.docker.local:8888/corestore.web:dev

    build:
      context: .
      dockerfile: CoreStore.Web/Dockerfile

networks:
 serene_net:
    external:
      name: serene